[package]
name = "rust_bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_bindings"
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
hex = "0.4.3"
pyo3 = { version = "0.24.0", features = ["extension-module"] }
rayon = "1.10.0"
flate2 = "1.1.0"
walkdir = "2.5.0"