[project]
name = "teleparser"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ronaldo S.A. Batista", email = "ronaldokun@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "typer>=0.15.2",
]

[project.scripts]
teleparser = "teleparser:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
]  
