[project]
name = "teleparser"
version = "0.1.0"
description = "A tool to parse CDR files from Brazilian Mobile operators."
readme = "README.md"
authors = [
    { name = "Ronaldo S.A. Batista", email = "ronaldokun@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "typer>=0.15.2",
]

[project.scripts]
tradutor-cdr = "teleparser.cli:process_cdrs"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pyinstaller>=6.12.0",
]

