[project]
name = "teleparser"
version = "0.1.0"
description = "A tool to parse CDR files from Brazilian Mobile operators."
readme = "README.md"
authors = [
    { name = "Ronaldo S.A. Batista", email = "ronaldokun@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "typer>=0.15.2",
]

[project.scripts]
process-cdrs = "teleparser.entrypoint:process_cdrs"


[build-system]
requires = ["setuptools>=42", "wheel", "nuitka", "toml"]
build-backend = "nuitka.distutils.Build"


[tool.nuitka]
# These are not recommended, but they make it obvious to have effect.
# boolean option, e.g. if you cared for C compilation commands, leading
# dashes are omitted
show-scons = true

# options with several values, e.g. avoid including modules, accepts
# list argument.
nofollow-import-to = ["*.tests", "*.distutils", "*.nbs"]

[dependency-groups]
dev = [
    "nuitka>=2.6.9",
]  
