[project]
name = "teleparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ronaldo S.A. Batista", email = "ronaldokun@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pyarrow>=19.0.1",
]

[project.scripts]
teleparser = "teleparser:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "setuptools>=75.8.1",
    "ydata-profiling>=4.12.2",

]
