SPECIFICATION = {'CallDataRecord': {'extensibility-implied': False,
                    'imports': {},
                    'object-classes': {},
                    'object-sets': {},
                    'tags': 'IMPLICIT',
                    'types': {'CallDataRecord': {'members': [{'name': 'singleCallDataRecord',
                                                              'type': 'UMTSGSMPLMNCallDataRecord'},
                                                             {'name': 'compositeCallDataRecord',
                                                              'tag': {'number': 1},
                                                              'type': 'CompositeCallDataRecord'}],
                                                 'type': 'CHOICE'},
                              'CompositeCallDataRecord': {'element': {'type': 'UMTSGSMPLMNCallDataRecord'},
                                                          'type': 'SEQUENCE '
                                                                  'OF'}},
                    'values': {}},
 'CallModules': {'extensibility-implied': False,
                 'imports': {},
                 'object-classes': {},
                 'object-sets': {},
                 'tags': 'IMPLICIT',
                 'types': {'MSOriginating': {'members': [{'name': 'tAC',
                                                          'optional': True,
                                                          'tag': {'number': 0},
                                                          'type': 'TAC'},
                                                         {'name': 'callIdentificationNumber',
                                                          'optional': True,
                                                          'tag': {'number': 1},
                                                          'type': 'CallIDNumber'},
                                                         {'name': 'recordSequenceNumber',
                                                          'optional': True,
                                                          'tag': {'number': 2},
                                                          'type': 'RecordSequenceNumber'},
                                                         {'name': 'typeOfCallingSubscriber',
                                                          'optional': True,
                                                          'tag': {'number': 3},
                                                          'type': 'TypeOfCallingSubscriber'},
                                                         {'name': 'callingPartyNumber',
                                                          'optional': True,
                                                          'tag': {'number': 4},
                                                          'type': 'AddressString'},
                                                         {'name': 'callingSubscriberIMSI',
                                                          'optional': True,
                                                          'tag': {'number': 5},
                                                          'type': 'IMSI'},
                                                         {'name': 'callingSubscriberIMEI',
                                                          'optional': True,
                                                          'tag': {'number': 6},
                                                          'type': 'IMEI'},
                                                         {'name': 'calledPartyNumber',
                                                          'optional': True,
                                                          'tag': {'number': 7},
                                                          'type': 'AddressString'},
                                                         {'name': 'disconnectingParty',
                                                          'optional': True,
                                                          'tag': {'number': 8},
                                                          'type': 'DisconnectingParty'},
                                                         {'name': 'dateForStartOfCharge',
                                                          'optional': True,
                                                          'tag': {'number': 9},
                                                          'type': 'Date'},
                                                         {'name': 'timeForStartOfCharge',
                                                          'optional': True,
                                                          'tag': {'number': 10},
                                                          'type': 'Time'},
                                                         {'name': 'timeForStopOfCharge',
                                                          'optional': True,
                                                          'tag': {'number': 11},
                                                          'type': 'Time'},
                                                         {'name': 'chargeableDuration',
                                                          'optional': True,
                                                          'tag': {'number': 12},
                                                          'type': 'Time'},
                                                         {'name': 'interruptionTime',
                                                          'optional': True,
                                                          'tag': {'number': 13},
                                                          'type': 'Time'},
                                                         {'name': 'timeFromRegisterSeizureToStartOfCharging',
                                                          'optional': True,
                                                          'tag': {'number': 14},
                                                          'type': 'Time'},
                                                         {'name': 'chargedParty',
                                                          'optional': True,
                                                          'tag': {'number': 15},
                                                          'type': 'ChargedParty'},
                                                         {'name': 'originForCharging',
                                                          'optional': True,
                                                          'tag': {'number': 16},
                                                          'type': 'ChargingOrigin'},
                                                         {'name': 'chargingCase',
                                                          'optional': True,
                                                          'tag': {'number': 17},
                                                          'type': 'ChargingCase'},
                                                         {'name': 'tariffClass',
                                                          'optional': True,
                                                          'tag': {'number': 18},
                                                          'type': 'TariffClass'},
                                                         {'name': 'tariffSwitchInd',
                                                          'optional': True,
                                                          'tag': {'number': 19},
                                                          'type': 'TariffSwitchInd'},
                                                         {'name': 'exchangeIdentity',
                                                          'optional': True,
                                                          'tag': {'number': 20},
                                                          'type': 'ExchangeIdentity'},
                                                         {'name': 'mSCIdentification',
                                                          'optional': True,
                                                          'tag': {'number': 21},
                                                          'type': 'AddressString'},
                                                         {'name': 'outgoingRoute',
                                                          'optional': True,
                                                          'tag': {'number': 22},
                                                          'type': 'Route'},
                                                         {'name': 'incomingRoute',
                                                          'optional': True,
                                                          'tag': {'number': 23},
                                                          'type': 'Route'},
                                                         {'name': 'miscellaneousInformation',
                                                          'optional': True,
                                                          'tag': {'number': 24},
                                                          'type': 'MiscellaneousInformation'},
                                                         {'name': 'originatingLocationNumber',
                                                          'optional': True,
                                                          'tag': {'number': 25},
                                                          'type': 'AddressString'},
                                                         {'name': 'timeForTCSeizureCalling',
                                                          'optional': True,
                                                          'tag': {'number': 26},
                                                          'type': 'Time'},
                                                         {'name': 'firstCallingLocationInformation',
                                                          'optional': True,
                                                          'tag': {'number': 27},
                                                          'type': 'LocationInformation'},
                                                         {'name': 'lastCallingLocationInformation',
                                                          'optional': True,
                                                          'tag': {'number': 28},
                                                          'type': 'LocationInformation'},
                                                         {'name': 'teleServiceCode',
                                                          'optional': True,
                                                          'tag': {'number': 29},
                                                          'type': 'TeleServiceCode'},
                                                         {'name': 'bearerServiceCode',
                                                          'optional': True,
                                                          'tag': {'number': 30},
                                                          'type': 'BearerServiceCode'},
                                                         {'name': 'transparencyIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 31},
                                                          'type': 'TransparencyIndicator'},
                                                         {'name': 'firstRadioChannelUsed',
                                                          'optional': True,
                                                          'tag': {'number': 32},
                                                          'type': 'FirstRadioChannelUsed'},
                                                         {'name': 'callPosition',
                                                          'optional': True,
                                                          'tag': {'number': 33},
                                                          'type': 'CallPosition'},
                                                         {'name': 'eosInfo',
                                                          'optional': True,
                                                          'tag': {'number': 34},
                                                          'type': 'Eosinfo'},
                                                         {'name': 'internalCauseAndLoc',
                                                          'optional': True,
                                                          'tag': {'number': 35},
                                                          'type': 'InternalCauseAndLoc'},
                                                         {'name': 'restartDuringCall',
                                                          'optional': True,
                                                          'tag': {'number': 36},
                                                          'type': 'NULL'},
                                                         {'name': 'restartDuringOutputIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 37},
                                                          'type': 'NULL'},
                                                         {'name': 'numberOfMeterPulses',
                                                          'optional': True,
                                                          'tag': {'number': 38},
                                                          'type': 'NumberOfMeterPulses'},
                                                         {'name': 'c7ChargingMessage',
                                                          'optional': True,
                                                          'tag': {'number': 39},
                                                          'type': 'C7ChargingMessage'},
                                                         {'name': 'c7FirstCHTMessage',
                                                          'optional': True,
                                                          'tag': {'number': 40},
                                                          'type': 'C7CHTMessage'},
                                                         {'name': 'c7SecondCHTMessage',
                                                          'optional': True,
                                                          'tag': {'number': 41},
                                                          'type': 'C7CHTMessage'},
                                                         {'name': 'calledPartyMNPInfo',
                                                          'optional': True,
                                                          'tag': {'number': 42},
                                                          'type': 'AddressString'},
                                                         {'name': 'carrierIdentificationCode',
                                                          'optional': True,
                                                          'tag': {'number': 43},
                                                          'type': 'CarrierIdentificationCode'},
                                                         {'name': 'dTMFUsed',
                                                          'optional': True,
                                                          'tag': {'number': 44},
                                                          'type': 'NULL'},
                                                         {'name': 'iCIOrdered',
                                                          'optional': True,
                                                          'tag': {'number': 45},
                                                          'type': 'NULL'},
                                                         {'name': 'outputForSubscriber',
                                                          'optional': True,
                                                          'tag': {'number': 46},
                                                          'type': 'OutputForSubscriber'},
                                                         {'name': 'iNMarkingOfMS',
                                                          'optional': True,
                                                          'tag': {'number': 47},
                                                          'type': 'INMarkingOfMS'},
                                                         {'name': 'lastPartialOutput',
                                                          'optional': True,
                                                          'tag': {'number': 48},
                                                          'type': 'NULL'},
                                                         {'name': 'partialOutputRecNum',
                                                          'optional': True,
                                                          'tag': {'number': 49},
                                                          'type': 'PartialOutputRecNum'},
                                                         {'name': 'cUGInterlockCode',
                                                          'optional': True,
                                                          'tag': {'number': 50},
                                                          'type': 'CUGInterlockCode'},
                                                         {'name': 'cUGIndex',
                                                          'optional': True,
                                                          'tag': {'number': 51},
                                                          'type': 'CUGIndex'},
                                                         {'name': 'cUGOutgoingAccessUsed',
                                                          'optional': True,
                                                          'tag': {'number': 52},
                                                          'type': 'NULL'},
                                                         {'name': 'cUGOutgoingAccessIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 53},
                                                          'type': 'NULL'},
                                                         {'name': 'regionalServiceUsed',
                                                          'optional': True,
                                                          'tag': {'number': 54},
                                                          'type': 'RegionalServiceUsed'},
                                                         {'name': 'regionDependentChargingOrigin',
                                                          'optional': True,
                                                          'tag': {'number': 55},
                                                          'type': 'ChargingOrigin'},
                                                         {'name': 'sSCode',
                                                          'optional': True,
                                                          'tag': {'number': 56},
                                                          'type': 'SSCode'},
                                                         {'name': 'channelAllocationPriorityLevel',
                                                          'optional': True,
                                                          'tag': {'number': 57},
                                                          'type': 'ChannelAllocationPriorityLevel'},
                                                         {'name': 'radioChannelProperty',
                                                          'optional': True,
                                                          'tag': {'number': 58},
                                                          'type': 'RadioChannelProperty'},
                                                         {'name': 'faultCode',
                                                          'optional': True,
                                                          'tag': {'number': 59},
                                                          'type': 'FaultCode'},
                                                         {'name': 'intermediateRate',
                                                          'optional': True,
                                                          'tag': {'number': 60},
                                                          'type': 'IntermediateRate'},
                                                         {'name': 'firstAssignedSpeechCoderVersion',
                                                          'optional': True,
                                                          'tag': {'number': 61},
                                                          'type': 'SpeechCoderVersion'},
                                                         {'name': 'speechCoderPreferenceList',
                                                          'optional': True,
                                                          'tag': {'number': 62},
                                                          'type': 'SpeechCoderPreferenceList'},
                                                         {'name': 'subscriptionType',
                                                          'optional': True,
                                                          'tag': {'number': 63},
                                                          'type': 'SubscriptionType'},
                                                         {'name': 'incompleteCallDataIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 64},
                                                          'type': 'NULL'},
                                                         {'name': 'incompleteCompositeCDRIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 65},
                                                          'type': 'NULL'},
                                                         {'name': 'switchIdentity',
                                                          'optional': True,
                                                          'tag': {'number': 67},
                                                          'type': 'SwitchIdentity'},
                                                         {'name': 'networkCallReference',
                                                          'optional': True,
                                                          'tag': {'number': 68},
                                                          'type': 'NetworkCallReference'},
                                                         {'name': 'frequencyBandSupported',
                                                          'optional': True,
                                                          'tag': {'number': 69},
                                                          'type': 'FrequencyBandSupported'},
                                                         {'name': 'disconnectionDueToSystemRecovery',
                                                          'optional': True,
                                                          'tag': {'number': 70},
                                                          'type': 'NULL'},
                                                         {'name': 'forloppDuringOutputIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 71},
                                                          'type': 'NULL'},
                                                         {'name': 'forloppReleaseDuringCall',
                                                          'optional': True,
                                                          'tag': {'number': 72},
                                                          'type': 'NULL'},
                                                         {'name': 'accountCode',
                                                          'optional': True,
                                                          'tag': {'number': 73},
                                                          'type': 'AccountCode'},
                                                         {'name': 'translatedNumber',
                                                          'optional': True,
                                                          'tag': {'number': 74},
                                                          'type': 'AddressString'},
                                                         {'name': 'bCSMTDPData1',
                                                          'optional': True,
                                                          'tag': {'number': 75},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData2',
                                                          'optional': True,
                                                          'tag': {'number': 76},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData3',
                                                          'optional': True,
                                                          'tag': {'number': 77},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData4',
                                                          'optional': True,
                                                          'tag': {'number': 78},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData5',
                                                          'optional': True,
                                                          'tag': {'number': 79},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData6',
                                                          'optional': True,
                                                          'tag': {'number': 80},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData7',
                                                          'optional': True,
                                                          'tag': {'number': 81},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData8',
                                                          'optional': True,
                                                          'tag': {'number': 82},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData9',
                                                          'optional': True,
                                                          'tag': {'number': 83},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'bCSMTDPData10',
                                                          'optional': True,
                                                          'tag': {'number': 84},
                                                          'type': 'CAMELTDPData'},
                                                         {'name': 'gSMCallReferenceNumber',
                                                          'optional': True,
                                                          'tag': {'number': 85},
                                                          'type': 'GSMCallReferenceNumber'},
                                                         {'name': 'mSCAddress',
                                                          'optional': True,
                                                          'tag': {'number': 86},
                                                          'type': 'AddressString'},
                                                         {'name': 'eMLPPPriorityLevel',
                                                          'optional': True,
                                                          'tag': {'number': 87},
                                                          'type': 'EMLPPPriorityLevel'},
                                                         {'name': 'positionAccuracy',
                                                          'optional': True,
                                                          'tag': {'number': 88},
                                                          'type': 'PositionAccuracy'},
                                                         {'name': 'userTerminalPosition',
                                                          'optional': True,
                                                          'tag': {'number': 89},
                                                          'type': 'UserTerminalPosition'},
                                                         {'name': 'acceptableChannelCodings',
                                                          'optional': True,
                                                          'tag': {'number': 90},
                                                          'type': 'ChannelCodings'},
                                                         {'name': 'incomingAssignedRoute',
                                                          'optional': True,
                                                          'tag': {'number': 91},
                                                          'type': 'Route'},
                                                         {'name': 'channelCodingUsed',
                                                          'optional': True,
                                                          'tag': {'number': 92},
                                                          'type': 'ChannelCodings'},
                                                         {'name': 'rANAPCauseCode',
                                                          'optional': True,
                                                          'tag': {'number': 93},
                                                          'type': 'RANAPCauseCode'},
                                                         {'name': 'gsmSCFAddress',
                                                          'optional': True,
                                                          'tag': {'number': 94},
                                                          'type': 'AddressString'},
                                                         {'name': 'fNURRequested',
                                                          'optional': True,
                                                          'tag': {'number': 95},
                                                          'type': 'FixedNetworkUserRate'},
                                                         {'name': 'aIURRequested',
                                                          'optional': True,
                                                          'tag': {'number': 96},
                                                          'type': 'AirInterfaceUserRate'},
                                                         {'name': 'numberOfChannelsRequested',
                                                          'optional': True,
                                                          'tag': {'number': 97},
                                                          'type': 'NumberOfChannels'},
                                                         {'name': 'bSSMAPCauseCode',
                                                          'optional': True,
                                                          'tag': {'number': 98},
                                                          'type': 'BSSMAPCauseCode'},
                                                         {'name': 'multimediaCall',
                                                          'optional': True,
                                                          'tag': {'number': 99},
                                                          'type': 'NULL'},
                                                         {'name': 'guaranteedBitRate',
                                                          'optional': True,
                                                          'tag': {'number': 100},
                                                          'type': 'BitRate'},
                                                         {'name': 'trafficClass',
                                                          'optional': True,
                                                          'tag': {'number': 101},
                                                          'type': 'TrafficClass'},
                                                         {'name': 'outputType',
                                                          'optional': True,
                                                          'tag': {'number': 102},
                                                          'type': 'OutputType'},
                                                         {'name': 'rNCidOfFirstRNC',
                                                          'optional': True,
                                                          'tag': {'number': 103},
                                                          'type': 'TargetRNCid'},
                                                         {'name': 'maxBitRateDownlink',
                                                          'optional': True,
                                                          'tag': {'number': 104},
                                                          'type': 'BitRate'},
                                                         {'name': 'maxBitRateUplink',
                                                          'optional': True,
                                                          'tag': {'number': 105},
                                                          'type': 'BitRate'},
                                                         {'name': 'transferDelay',
                                                          'optional': True,
                                                          'tag': {'number': 106},
                                                          'type': 'TransferDelay'},
                                                         {'name': 'deliveryOfErroneousSDU1',
                                                          'optional': True,
                                                          'tag': {'number': 107},
                                                          'type': 'DeliveryOfErroneousSDU'},
                                                         {'name': 'deliveryOfErroneousSDU2',
                                                          'optional': True,
                                                          'tag': {'number': 108},
                                                          'type': 'DeliveryOfErroneousSDU'},
                                                         {'name': 'deliveryOfErroneousSDU3',
                                                          'optional': True,
                                                          'tag': {'number': 109},
                                                          'type': 'DeliveryOfErroneousSDU'},
                                                         {'name': 'residualBitErrorRatio1',
                                                          'optional': True,
                                                          'tag': {'number': 110},
                                                          'type': 'ErrorRatio'},
                                                         {'name': 'residualBitErrorRatio2',
                                                          'optional': True,
                                                          'tag': {'number': 111},
                                                          'type': 'ErrorRatio'},
                                                         {'name': 'residualBitErrorRatio3',
                                                          'optional': True,
                                                          'tag': {'number': 112},
                                                          'type': 'ErrorRatio'},
                                                         {'name': 'sDUErrorRatio1',
                                                          'optional': True,
                                                          'tag': {'number': 113},
                                                          'type': 'ErrorRatio'},
                                                         {'name': 'sDUErrorRatio2',
                                                          'optional': True,
                                                          'tag': {'number': 114},
                                                          'type': 'ErrorRatio'},
                                                         {'name': 'sDUErrorRatio3',
                                                          'optional': True,
                                                          'tag': {'number': 115},
                                                          'type': 'ErrorRatio'},
                                                         {'name': 'aCMChargingIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 116},
                                                          'type': 'ChargingIndicator'},
                                                         {'name': 'aNMChargingIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 117},
                                                          'type': 'ChargingIndicator'},
                                                         {'name': 'carrierInformationBackward',
                                                          'optional': True,
                                                          'tag': {'number': 118},
                                                          'type': 'TransitCarrierInfo'},
                                                         {'name': 'chargeInformation',
                                                          'optional': True,
                                                          'tag': {'number': 119},
                                                          'type': 'ChargeInformation'},
                                                         {'name': 'disconnectionDate',
                                                          'optional': True,
                                                          'tag': {'number': 120},
                                                          'type': 'Date'},
                                                         {'name': 'disconnectionTime',
                                                          'optional': True,
                                                          'tag': {'number': 124},
                                                          'type': 'Time'},
                                                         {'name': 'originatingCarrier',
                                                          'optional': True,
                                                          'tag': {'number': 125},
                                                          'type': 'CarrierInfo'},
                                                         {'name': 'originatingChargeArea',
                                                          'optional': True,
                                                          'tag': {'number': 126},
                                                          'type': 'ChargeAreaCode'},
                                                         {'name': 'tDSCounter',
                                                          'optional': True,
                                                          'tag': {'number': 127},
                                                          'type': 'Counter'},
                                                         {'name': 'terminatingAccessISDN',
                                                          'optional': True,
                                                          'tag': {'number': 128},
                                                          'type': 'NULL'},
                                                         {'name': 'terminatingCarrier',
                                                          'optional': True,
                                                          'tag': {'number': 129},
                                                          'type': 'CarrierInfo'},
                                                         {'name': 'terminatingChargeArea',
                                                          'optional': True,
                                                          'tag': {'number': 130},
                                                          'type': 'ChargeAreaCode'},
                                                         {'name': 'terminatingMobileUserClass1',
                                                          'optional': True,
                                                          'tag': {'number': 131},
                                                          'type': 'MobileUserClass1'},
                                                         {'name': 'terminatingMobileUserClass2',
                                                          'optional': True,
                                                          'tag': {'number': 132},
                                                          'type': 'MobileUserClass2'},
                                                         {'name': 'terminatingUserClass',
                                                          'optional': True,
                                                          'tag': {'number': 133},
                                                          'type': 'UserClass'},
                                                         {'name': 'contractorNumber',
                                                          'optional': True,
                                                          'tag': {'number': 134},
                                                          'type': 'AddressString'},
                                                         {'name': 'carrierInformation',
                                                          'optional': True,
                                                          'tag': {'number': 135},
                                                          'type': 'CarrierInformation'},
                                                         {'name': 'carrierSelectionSubstitutionInformation',
                                                          'optional': True,
                                                          'tag': {'number': 136},
                                                          'type': 'CarrierSelectionSubstitutionInformation'},
                                                         {'name': 'chargeNumber',
                                                          'optional': True,
                                                          'tag': {'number': 137},
                                                          'type': 'AddressString'},
                                                         {'name': 'interExchangeCarrierIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 138},
                                                          'type': 'NULL'},
                                                         {'name': 'originatingLineInformation',
                                                          'optional': True,
                                                          'tag': {'number': 139},
                                                          'type': 'OriginatingLineInformation'},
                                                         {'name': 'selectedCodec',
                                                          'optional': True,
                                                          'tag': {'number': 140},
                                                          'type': 'SelectedCodec'},
                                                         {'name': 'wPSCallIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 141},
                                                          'type': 'NULL'},
                                                         {'name': 'originatedCode',
                                                          'optional': True,
                                                          'tag': {'number': 66},
                                                          'type': 'OriginatedCode'},
                                                         {'name': 'reroutingIndicator',
                                                          'optional': True,
                                                          'tag': {'number': 121},
                                                          'type': 'NULL'},
                                                         {'name': 'invocationOfCallHold',
                                                          'optional': True,
                                                          'tag': {'number': 122},
                                                          'type': 'NULL'},
                                                         {'name': 'retrievalOfHeldCall',
                                                          'optional': True,
                                                          'tag': {'number': 123},
                                                          'type': 'NULL'}],
                                             'type': 'SET'},
                           'Transit': {'members': [{'name': 'tAC',
                                                    'optional': True,
                                                    'tag': {'number': 0},
                                                    'type': 'TAC'},
                                                   {'name': 'callIdentificationNumber',
                                                    'optional': True,
                                                    'tag': {'number': 1},
                                                    'type': 'CallIDNumber'},
                                                   {'name': 'recordSequenceNumber',
                                                    'optional': True,
                                                    'tag': {'number': 2},
                                                    'type': 'RecordSequenceNumber'},
                                                   {'name': 'typeOfCallingSubscriber',
                                                    'optional': True,
                                                    'tag': {'number': 3},
                                                    'type': 'TypeOfCallingSubscriber'},
                                                   {'name': 'callingPartyNumber',
                                                    'optional': True,
                                                    'tag': {'number': 4},
                                                    'type': 'AddressString'},
                                                   {'name': 'calledPartyNumber',
                                                    'optional': True,
                                                    'tag': {'number': 5},
                                                    'type': 'AddressString'},
                                                   {'name': 'calledSubscriberIMSI',
                                                    'optional': True,
                                                    'tag': {'number': 6},
                                                    'type': 'IMSI'},
                                                   {'name': 'disconnectingParty',
                                                    'optional': True,
                                                    'tag': {'number': 7},
                                                    'type': 'DisconnectingParty'},
                                                   {'name': 'dateForStartOfCharge',
                                                    'optional': True,
                                                    'tag': {'number': 8},
                                                    'type': 'Date'},
                                                   {'name': 'timeForStartOfCharge',
                                                    'optional': True,
                                                    'tag': {'number': 9},
                                                    'type': 'Time'},
                                                   {'name': 'timeForStopOfCharge',
                                                    'optional': True,
                                                    'tag': {'number': 10},
                                                    'type': 'Time'},
                                                   {'name': 'chargeableDuration',
                                                    'optional': True,
                                                    'tag': {'number': 11},
                                                    'type': 'Time'},
                                                   {'name': 'interruptionTime',
                                                    'optional': True,
                                                    'tag': {'number': 12},
                                                    'type': 'Time'},
                                                   {'name': 'timeFromRegisterSeizureToStartOfCharging',
                                                    'optional': True,
                                                    'tag': {'number': 13},
                                                    'type': 'Time'},
                                                   {'name': 'chargedParty',
                                                    'optional': True,
                                                    'tag': {'number': 14},
                                                    'type': 'ChargedParty'},
                                                   {'name': 'originForCharging',
                                                    'optional': True,
                                                    'tag': {'number': 15},
                                                    'type': 'ChargingOrigin'},
                                                   {'name': 'tariffClass',
                                                    'optional': True,
                                                    'tag': {'number': 16},
                                                    'type': 'TariffClass'},
                                                   {'name': 'tariffSwitchInd',
                                                    'optional': True,
                                                    'tag': {'number': 17},
                                                    'type': 'TariffSwitchInd'},
                                                   {'name': 'numberOfMeterPulses',
                                                    'optional': True,
                                                    'tag': {'number': 18},
                                                    'type': 'NumberOfMeterPulses'},
                                                   {'name': 'exchangeIdentity',
                                                    'optional': True,
                                                    'tag': {'number': 19},
                                                    'type': 'ExchangeIdentity'},
                                                   {'name': 'mSCIdentification',
                                                    'optional': True,
                                                    'tag': {'number': 20},
                                                    'type': 'AddressString'},
                                                   {'name': 'outgoingRoute',
                                                    'optional': True,
                                                    'tag': {'number': 21},
                                                    'type': 'Route'},
                                                   {'name': 'incomingRoute',
                                                    'optional': True,
                                                    'tag': {'number': 22},
                                                    'type': 'Route'},
                                                   {'name': 'miscellaneousInformation',
                                                    'optional': True,
                                                    'tag': {'number': 23},
                                                    'type': 'MiscellaneousInformation'},
                                                   {'name': 'iNMarkingOfMS',
                                                    'optional': True,
                                                    'tag': {'number': 25},
                                                    'type': 'INMarkingOfMS'},
                                                   {'name': 'callPosition',
                                                    'optional': True,
                                                    'tag': {'number': 26},
                                                    'type': 'CallPosition'},
                                                   {'name': 'eosInfo',
                                                    'optional': True,
                                                    'tag': {'number': 27},
                                                    'type': 'EosInfo'},
                                                   {'name': 'internalCauseAndLoc',
                                                    'optional': True,
                                                    'tag': {'number': 28},
                                                    'type': 'InternalCauseAndLoc'},
                                                   {'name': 'originalCalledNumber',
                                                    'optional': True,
                                                    'tag': {'number': 29},
                                                    'type': 'AddressString'},
                                                   {'name': 'redirectingNumber',
                                                    'optional': True,
                                                    'tag': {'number': 30},
                                                    'type': 'AddressString'},
                                                   {'name': 'redirectionCounter',
                                                    'optional': True,
                                                    'tag': {'number': 31},
                                                    'type': 'RedirectionCounter'},
                                                   {'name': 'redirectingDropBackNumber',
                                                    'optional': True,
                                                    'tag': {'number': 32},
                                                    'type': 'AddressString'},
                                                   {'name': 'redirectingDropBack',
                                                    'optional': True,
                                                    'tag': {'number': 33},
                                                    'type': 'NULL'},
                                                   {'name': 'restartDuringCall',
                                                    'optional': True,
                                                    'tag': {'number': 34},
                                                    'type': 'NULL'},
                                                   {'name': 'restartDuringOutputIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 35},
                                                    'type': 'NULL'},
                                                   {'name': 'iCIOrdered',
                                                    'optional': True,
                                                    'tag': {'number': 36},
                                                    'type': 'NULL'},
                                                   {'name': 'outputForSubscriber',
                                                    'optional': True,
                                                    'tag': {'number': 37},
                                                    'type': 'OutputForSubscriber'},
                                                   {'name': 'lastPartialOutput',
                                                    'optional': True,
                                                    'tag': {'number': 38},
                                                    'type': 'NULL'},
                                                   {'name': 'partialOutputRecNum',
                                                    'optional': True,
                                                    'tag': {'number': 39},
                                                    'type': 'PartialOutputRecNum'},
                                                   {'name': 'relatedCallNumber',
                                                    'optional': True,
                                                    'tag': {'number': 40},
                                                    'type': 'CallIDNumber'},
                                                   {'name': 'faultCode',
                                                    'optional': True,
                                                    'tag': {'number': 41},
                                                    'type': 'FaultCode'},
                                                   {'name': 'subscriptionType',
                                                    'optional': True,
                                                    'tag': {'number': 42},
                                                    'type': 'SubscriptionType'},
                                                   {'name': 'incompleteCallDataIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 43},
                                                    'type': 'NULL'},
                                                   {'name': 'incompleteCompositeCDRIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 44},
                                                    'type': 'NULL'},
                                                   {'name': 'switchIdentity',
                                                    'optional': True,
                                                    'tag': {'number': 45},
                                                    'type': 'SwitchIdentity'},
                                                   {'name': 'networkCallReference',
                                                    'optional': True,
                                                    'tag': {'number': 46},
                                                    'type': 'NetworkCallReference'},
                                                   {'name': 'disconnectionDueToSystemRecovery',
                                                    'optional': True,
                                                    'tag': {'number': 47},
                                                    'type': 'NULL'},
                                                   {'name': 'forloppDuringOutputIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 48},
                                                    'type': 'NULL'},
                                                   {'name': 'forloppReleaseDuringCall',
                                                    'optional': True,
                                                    'tag': {'number': 49},
                                                    'type': 'NULL'},
                                                   {'name': 'translatedNumber',
                                                    'optional': True,
                                                    'tag': {'number': 50},
                                                    'type': 'AddressString'},
                                                   {'name': 'bCSMTDPData1',
                                                    'optional': True,
                                                    'tag': {'number': 51},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData2',
                                                    'optional': True,
                                                    'tag': {'number': 52},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData3',
                                                    'optional': True,
                                                    'tag': {'number': 53},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData4',
                                                    'optional': True,
                                                    'tag': {'number': 54},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData5',
                                                    'optional': True,
                                                    'tag': {'number': 55},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData6',
                                                    'optional': True,
                                                    'tag': {'number': 56},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData7',
                                                    'optional': True,
                                                    'tag': {'number': 57},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData8',
                                                    'optional': True,
                                                    'tag': {'number': 58},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData9',
                                                    'optional': True,
                                                    'tag': {'number': 59},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'bCSMTDPData10',
                                                    'optional': True,
                                                    'tag': {'number': 60},
                                                    'type': 'CAMELTDPData'},
                                                   {'name': 'gSMCallReferenceNumber',
                                                    'optional': True,
                                                    'tag': {'number': 61},
                                                    'type': 'GSMCallReferenceNumber'},
                                                   {'name': 'c7ChargingMessage',
                                                    'optional': True,
                                                    'tag': {'number': 62},
                                                    'type': 'C7ChargingMessage'},
                                                   {'name': 'c7FirstCHTMessage',
                                                    'optional': True,
                                                    'tag': {'number': 63},
                                                    'type': 'C7CHTMessage'},
                                                   {'name': 'c7SecondCHTMessage',
                                                    'optional': True,
                                                    'tag': {'number': 64},
                                                    'type': 'C7CHTMessage'},
                                                   {'name': 'aCMChargingIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 65},
                                                    'type': 'ChargingIndicator'},
                                                   {'name': 'aNMChargingIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 66},
                                                    'type': 'ChargingIndicator'},
                                                   {'name': 'mSCAddress',
                                                    'optional': True,
                                                    'tag': {'number': 67},
                                                    'type': 'AddressString'},
                                                   {'name': 'carrierInformationBackward',
                                                    'optional': True,
                                                    'tag': {'number': 68},
                                                    'type': 'TransitCarrierInfo'},
                                                   {'name': 'carrierInformationForward',
                                                    'optional': True,
                                                    'tag': {'number': 69},
                                                    'type': 'TransitCarrierInfo'},
                                                   {'name': 'chargeInformation',
                                                    'optional': True,
                                                    'tag': {'number': 70},
                                                    'type': 'ChargeInformation'},
                                                   {'name': 'disconnectionDate',
                                                    'optional': True,
                                                    'tag': {'number': 71},
                                                    'type': 'Date'},
                                                   {'name': 'disconnectionTime',
                                                    'optional': True,
                                                    'tag': {'number': 72},
                                                    'type': 'Time'},
                                                   {'name': 'entryPOICA',
                                                    'optional': True,
                                                    'tag': {'number': 73},
                                                    'type': 'ChargeAreaCode'},
                                                   {'name': 'exitPOICA',
                                                    'optional': True,
                                                    'tag': {'number': 74},
                                                    'type': 'ChargeAreaCode'},
                                                   {'name': 'internationalCallIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 75},
                                                    'type': 'NULL'},
                                                   {'name': 'mobileUserClass1',
                                                    'optional': True,
                                                    'tag': {'number': 76},
                                                    'type': 'MobileUserClass1'},
                                                   {'name': 'mobileUserClass2',
                                                    'optional': True,
                                                    'tag': {'number': 77},
                                                    'type': 'MobileUserClass2'},
                                                   {'name': 'originatingAccessISDN',
                                                    'optional': True,
                                                    'tag': {'number': 78},
                                                    'type': 'NULL'},
                                                   {'name': 'originatingCarrier',
                                                    'optional': True,
                                                    'tag': {'number': 79},
                                                    'type': 'CarrierInfo'},
                                                   {'name': 'originatingChargeArea',
                                                    'optional': True,
                                                    'tag': {'number': 80},
                                                    'type': 'ChargeAreaCode'},
                                                   {'name': 'tDSCounter',
                                                    'optional': True,
                                                    'tag': {'number': 81},
                                                    'type': 'Counter'},
                                                   {'name': 'terminatingAccessISDN',
                                                    'optional': True,
                                                    'tag': {'number': 82},
                                                    'type': 'NULL'},
                                                   {'name': 'terminatingCarrier',
                                                    'optional': True,
                                                    'tag': {'number': 83},
                                                    'type': 'CarrierInfo'},
                                                   {'name': 'terminatingChargeArea',
                                                    'optional': True,
                                                    'tag': {'number': 84},
                                                    'type': 'ChargeAreaCode'},
                                                   {'name': 'terminatingMobileUserClass1',
                                                    'optional': True,
                                                    'tag': {'number': 85},
                                                    'type': 'MobileUserClass1'},
                                                   {'name': 'terminatingMobileUserClass2',
                                                    'optional': True,
                                                    'tag': {'number': 86},
                                                    'type': 'MobileUserClass2'},
                                                   {'name': 'contractorNumber',
                                                    'optional': True,
                                                    'tag': {'number': 87},
                                                    'type': 'AddressString'},
                                                   {'name': 'terminatingUserClass',
                                                    'optional': True,
                                                    'tag': {'number': 88},
                                                    'type': 'UserClass'},
                                                   {'name': 'userClass',
                                                    'optional': True,
                                                    'tag': {'number': 89},
                                                    'type': 'UserClass'},
                                                   {'name': 'calledPartyMNPInfo',
                                                    'optional': True,
                                                    'tag': {'number': 90},
                                                    'type': 'AddressString'},
                                                   {'name': 'chargeNumber',
                                                    'optional': True,
                                                    'tag': {'number': 91},
                                                    'type': 'AddressString'},
                                                   {'name': 'originatingLineInformation',
                                                    'optional': True,
                                                    'tag': {'number': 92},
                                                    'type': 'OriginatingLineInformation'},
                                                   {'name': 'multimediaInformation',
                                                    'optional': True,
                                                    'tag': {'number': 93},
                                                    'type': 'MultimediaInformation'},
                                                   {'name': 'outputType',
                                                    'optional': True,
                                                    'tag': {'number': 102},
                                                    'type': 'OutputType'},
                                                   {'name': 'originatedCode',
                                                    'optional': True,
                                                    'tag': {'number': 24},
                                                    'type': 'OriginatedCode'},
                                                   {'name': 'reroutingIndicator',
                                                    'optional': True,
                                                    'tag': {'number': 121},
                                                    'type': 'NULL'}],
                                       'type': 'SET'}},
                 'values': {}},
 'EventModules': {'extensibility-implied': False,
                  'imports': {},
                  'object-classes': {},
                  'object-sets': {},
                  'tags': 'IMPLICIT',
                  'types': {'EventModule': {'members': [{'name': 'aoCEventModule',
                                                         'tag': {'number': 10},
                                                         'type': 'AoCEventModule'},
                                                        {'name': 'sSInvocationEventModule',
                                                         'tag': {'number': 11},
                                                         'type': 'SSIEventModule'},
                                                        {'name': 'serviceSwitchEventModule',
                                                         'tag': {'number': 12},
                                                         'type': 'ServiceSwitchEventModule'},
                                                        {'name': 'iNServiceDataEventModule',
                                                         'tag': {'number': 16},
                                                         'type': 'INServiceDataEventModule'},
                                                        {'name': 'chargeRateChangeEventModule',
                                                         'tag': {'number': 20},
                                                         'type': 'ChargeRateChangeEventModule'},
                                                        {'name': 'iSDNSSInvocationEventModule',
                                                         'tag': {'number': 23},
                                                         'type': 'ISDNSSInvocationEventModule'},
                                                        {'name': 'handOverEventModule',
                                                         'tag': {'number': 25},
                                                         'type': 'HandOverEventModule'}],
                                            'type': 'CHOICE'}},
                  'values': {}},
 'TaggedData': {'extensibility-implied': False,
                'imports': {},
                'object-classes': {},
                'object-sets': {},
                'tags': 'IMPLICIT',
                'types': {'UILayerProtocol': {'type': 'ENUMERATED',
                                              'values': [('v110-X30', 1),
                                                         ('g711mulaw', 2),
                                                         ('g711Alaw', 3),
                                                         ('g721-32000bps-I460',
                                                          4),
                                                         ('h221-H242', 5),
                                                         ('h223-H245', 6),
                                                         ('nonITU-T', 7),
                                                         ('v120', 8),
                                                         ('x31', 9),
                                                         ('vSELP-Speech', 10)]},
                          'UnsuccessfulPositioningDataReason': {'type': 'ENUMERATED',
                                                                'values': [('systemError',
                                                                            0),
                                                                           ('userDeniedDueToPrivacyVerification',
                                                                            1)]},
                          'UserClass': {'size': [1], 'type': 'OCTET STRING'},
                          'UserRate': {'type': 'ENUMERATED',
                                       'values': [('uRIndNeg', 0),
                                                  ('uR600bps', 1),
                                                  ('uR1200bps', 2),
                                                  ('uR2400bps', 3),
                                                  ('uR3600bps', 4),
                                                  ('uR4800bps', 5),
                                                  ('uR7200bps', 6),
                                                  ('uR8000bps', 7),
                                                  ('uR9600bps', 8),
                                                  ('uR14400bps', 9),
                                                  ('uR16000bps', 10),
                                                  ('uR19200bps', 11),
                                                  ('uR32000bps', 12),
                                                  ('uR38400bps', 13),
                                                  ('uR48000bps', 14),
                                                  ('uR56000bps', 15),
                                                  ('uR64000bps', 16),
                                                  ('uR38400bps1', 17),
                                                  ('uR57600bps', 18),
                                                  ('uR28800bps', 19),
                                                  ('uR134-5bps', 21),
                                                  ('uR100bps', 22),
                                                  ('uR75bps1200bps', 23),
                                                  ('uR1200bps75bps', 24),
                                                  ('uR50bps', 25),
                                                  ('uR75bps', 26),
                                                  ('uR110bps', 27),
                                                  ('uR150bps', 28),
                                                  ('uR200bps', 29),
                                                  ('uR300bps', 30),
                                                  ('uR12000bps', 31)]},
                          'UserTerminalPosition': {'size': [7],
                                                   'type': 'OCTET STRING'},
                          'UserToUserService1Information': {'size': [1],
                                                            'type': 'OCTET '
                                                                    'STRING'}},
                'values': {}}}